### ISSUE TITLE
请问下nodejs的版本

### ISSUE THREAD

**Issue by Torah** [TrumanDu/bmap#2]
现在安装不上这个插件，报错。如果近期无法更新，能不能写一下这个插件的nodejs版本是多少？

**Comment by TrumanDu** [comment]
```8.5.x```

**Comment by Torah** [comment]
再请问一下，这个插件怎样发布编译版本？

**Comment by TrumanDu** [comment]
`npm run build`
查看readme,
不介意的话，给个star
